project_id = "mklfiunuhaaunytvtnfo"

[functions.admin-api-config]
verify_jwt = true

[functions.ai-chat-process]
verify_jwt = true

[functions.capture-attachments]
verify_jwt = true

[functions.check-monitoring]
verify_jwt = false

[functions.create-monitoring]
verify_jwt = true

[functions.download-attachments]
verify_jwt = true

[functions.escavador-callback]
verify_jwt = false

[functions.generate-pdf-dossier]
verify_jwt = true

[functions.get-process-details]
verify_jwt = true

[functions.judit-callback]
verify_jwt = false

[functions.manage-credentials]
verify_jwt = true

[functions.search-criminal-records]
verify_jwt = true

[functions.search-diarios-oficiais]
verify_jwt = true

[functions.search-processes]
verify_jwt = true

[functions.search-registration-data]
verify_jwt = true
